# Generated by Django 4.2 on 2023-07-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='default_username', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.CharField(default='', max_length=80),
        ),
    ]
