# Generated by Django 4.2 on 2023-07-02 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_username_alter_user_dob'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
