# Generated by Django 4.2 on 2023-07-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_customuser_remove_userprofile_name_delete_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
